// Session
const SET_TOKEN = 'SET_TOKEN'

// User
const SET_USER = 'SET_USER'
const CLEAR_USER = 'CLEAR_USER'
const USER_ERRORS = 'USER_ERRORS'
const LOADING_USER = 'LOADING_USER'
const CLEAR_IS_USER_LOADING = 'CLEAR_IS_USER_LOADING'

// ERRORS
const SET_ERRORS = 'SET_ERRORS'
const CLEAR_ERRORS = 'CLEAR_ERRORS'

// LISTS
const SET_LISTS = 'SET_LISTS'
const LOADING_LISTS = 'LOADING_LISTS'
const CREATE_LIST = 'CREATE_LIST'
const UPDATE_LIST = 'UPDATE_LIST'
const DELETE_LIST = 'DELETE_LIST'
const LOADING_SINGLE_LIST = 'LOADING_SINGLE_LIST'

export {
    // Session
    SET_TOKEN,

    // User
    SET_USER,
    USER_ERRORS,
    CLEAR_USER,
    LOADING_USER,
    CLEAR_IS_USER_LOADING,

    // ERRORS
    SET_ERRORS,
    CLEAR_ERRORS,

    // LISTS
    SET_LISTS,
    LOADING_LISTS,
    CREATE_LIST,
    UPDATE_LIST,
    DELETE_LIST,
    LOADING_SINGLE_LIST
}
