// Session
const SET_TOKEN = 'SET_TOKEN'

// User
const SET_USER = 'SET_USER'
const CLEAR_USER = 'CLEAR_USER'
const USER_ERRORS = 'USER_ERRORS'
const CLEAR_ERRORS = 'CLEAR_ERRRORS'
const LOADING_USER = 'LOADING_USER'
const CLEAR_IS_USER_LOADING = 'CLEAR_IS_USER_LOADING'

// ERRORS
const SET_ERRORS = 'SET_ERRORS'

// CATEGORIES
const SET_CATEGORIES = 'SET_CATEGORIES'
const LOADING_CATEGORIES = 'LOADING_CATEGORIES'
const CREATE_CATEGORY = 'CREATE_CATEGORY'
const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
const DELETE_CATEGORY = 'DELETE_CATEGORY'
const LOADING_SINGLE_CATEGORY = 'LOADING_SINGLE_CATEGORY'

export {
    // Session
    SET_TOKEN,

    // User
    SET_USER,
    USER_ERRORS,
    CLEAR_USER,
    CLEAR_ERRORS,
    LOADING_USER,
    CLEAR_IS_USER_LOADING,

    // ERRORS
    SET_ERRORS,

    // Categories
    SET_CATEGORIES,
    LOADING_CATEGORIES,
    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,
    LOADING_SINGLE_CATEGORY
}
